version: "3.8"

services:
  psql:
    image: postgres:alpine
    container_name: rbac-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rbac
      - POSTGRES_DB=rbac
      - POSTGRES_PASSWORD=super-secret
    restart: always
    healthcheck:
      test: pg_isready -U rbac -d rbac
      interval: 10s
      timeout: 8s
      retries: 5
    networks:
      - rbac-net

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: rbac-cache
    networks:
      - rbac-net
        
  
networks:
  rbac-net:
    driver: bridge
  
