POST http://localhost:8000/api/mobile/verify-token
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|S8dXBuRumNV42jYOORNbCY2b3iOJOEQFvgHCB4s3287e84f8

{
"phoneToken": "530260a3"
}
