PATCH http://localhost:8000/api/verify-two-factor/1?expires=1709929630&signature=dfefd7f5c4b9a7f2cc4beb3a48b1a8cacdc098edc292150d72fc6fe931fa77da
Accept: application/json
Content-Type: application/json

{
"token": "8060"
}
