<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Log;

class LoginRequest extends FormRequest
{

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            //
            'email' => ['required', 'email'],
            'password' => ['required', 'min:6', 'string'],
            'g-recaptcha-response' => ['required','captcha']
        ];
    }

    /**
     * Get the error messages for the defined validation rules.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'email.required' => 'El correo electrónico es requerido',
            'email.email' => 'El correo electrónico no es válido',
            'password.required' => 'La contraseña es requerida',
            'password.min' => 'La contraseña debe tener al menos 6 caracteres',
            'password.string' => 'La contraseña debe ser un texto',
            'g-recaptcha-response.required' => 'El captcha es requerido',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        if ($validator->errors()->has('g-recaptcha-response')) {
            Log::alert('Intento de login con captcha inválido', ['ip' => $this->ip()]);
            response('Forbidden', 403)->send();
            exit;
        }

        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }

}
